# Generated by Django 5.1.7 on 2025-03-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USUARIO_NOME_COMPLETO', models.CharField(max_length=200)),
                ('USUARIO_EMAIL', models.EmailField(max_length=200)),
                ('USUARIO_SENHA', models.CharField(max_length=50)),
                ('USUARIO_CRIADO_EM', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fc_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MES_ATUAL', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'fc_mes',
            },
        ),
        migrations.CreateModel(
            name='FinancasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FINANCAS_RECEITAS', models.FloatField()),
                ('FINANCAS_DESPESAS', models.FloatField()),
                ('FINANCAS_BALANCO', models.FloatField(blank=True)),
                ('FINANCAS_CRIADO_EM', models.DateTimeField(auto_now=True)),
                ('FINANCAS_ANO', models.IntegerField()),
                ('ID_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan_certo.cadastrousuario')),
                ('ID_MES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan_certo.meses')),
            ],
            options={
                'db_table': 'fc_financas_usuario',
            },
        ),
    ]
