# Generated by Django 5.1.7 on 2025-03-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fc_usuarios',
            },
        ),
    ]
