# Generated by Django 5.1.7 on 2025-04-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USUARIO_NOME_COMPLETO', models.CharField(max_length=200)),
                ('USUARIO_EMAIL', models.EmailField(max_length=200)),
                ('USUARIO_SENHA', models.CharField(max_length=50)),
                ('USUARIO_CRIADO_EM', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fc_usuarios',
            },
        ),
        migrations.CreateModel(
            name='FinancasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MES_ATUAL', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('FINANCAS_RECEITAS', models.FloatField()),
                ('FINANCAS_DESPESAS', models.FloatField()),
                ('FINANCAS_BALANCO', models.FloatField(blank=True)),
                ('FINANCAS_CRIADO_EM', models.DateTimeField(auto_now=True)),
                ('FINANCAS_ANO', models.IntegerField()),
                ('ID_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan_certo.cadastrousuario')),
            ],
            options={
                'db_table': 'fc_financas_usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MES_ATUAL', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('ANO_META', models.IntegerField()),
                ('USUARIO_META', models.FloatField()),
                ('USUARIO_ENTRADA', models.FloatField(blank=True, null=True)),
                ('META_CRIADO_EM', models.DateTimeField(auto_now_add=True)),
                ('ATUALIZADO_EM', models.DateTimeField(auto_now=True)),
                ('ID_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan_certo.cadastrousuario')),
            ],
            options={
                'db_table': 'fc_meta_usuario',
                'constraints': [models.UniqueConstraint(fields=('ID_USUARIO', 'MES_ATUAL', 'ANO_META'), name='unique_usuario_meta')],
            },
        ),
    ]
