# Generated by Django 5.1.7 on 2025-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan_certo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrousuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
