# Generated by Django 5.1.7 on 2025-03-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan_certo', '0002_alter_cadastrousuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrousuario',
            old_name='email',
            new_name='USUARIO_EMAIL',
        ),
        migrations.RenameField(
            model_name='cadastrousuario',
            old_name='id',
            new_name='USUARIO_ID',
        ),
        migrations.RenameField(
            model_name='cadastrousuario',
            old_name='nomeCompleto',
            new_name='USUARIO_NOME_COMPLETO',
        ),
        migrations.RenameField(
            model_name='cadastrousuario',
            old_name='senha',
            new_name='USUARIO_SENHA',
        ),
        migrations.AddField(
            model_name='cadastrousuario',
            name='USUARIO_CRIADO_EM',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
